apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "config1.txt" "config2.txt" "config3.txt" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}
